### ISSUE TITLE
create command line tools

### ISSUE THREAD

**Issue by tallenaz** [sul-dlss/libsys-webforms#101]
we want, maybe, rake tasks for the batch uploads, and maybe also for management reports.

**Comment by tallenaz** [comment]
A uni_updates_batch has constraints on the batch_id and the action -- these need to be assigned before creation.

**Comment by dlrueda** [comment]
morison needs to call rake task on libsys-webforms-dev.  maybe set up keypair for ssh?  or cgi script?

same for bodoni and libsys-webforms-prod.

need mount point between bodoni/libsys-webforms-prod for /s/SUL
(barcode file can live in same place as now, mount point between morison/libsys-webforms-dev is at /s/SUL) 

Will need to nail down format of ssh command performed on Symphony server

**Comment by tallenaz** [comment]
It's worth investigating whether we could use curl to post requests to the app for this. The main barrier would be getting through authentication.

**Comment by tallenaz** [comment]
I couldn't get curl to work because the app is behind webauth. Tomorrow afternoon, I'll work on getting the keypair set up for ssh, and I'll review the rake tasks to make sure they still do what we need them to do.

**Comment by jgreben** [comment]
@tallenaz We could probably modify the Apache config to allow a curl request from morison or bodoni, if you haven't made that much progress on the ssh keypair...
