### ISSUE TITLE
Create forms for Management Reports

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/libsys-webforms#110]
http://sulohsdev1.stanford.edu/morison/batch/mgt_rpt_auth.mgt_rpts

**Comment by jgreben** [comment]
Working on Encumbrance Report #129 first.

**Comment by tallenaz** [comment]
http://sulohsdev1.stanford.edu/morison/batch/circ_stats_rpt.request
http://sulohsdev1.stanford.edu/morison/batch/shelf_sel.request
etc.

**Comment by tallenaz** [comment]
Remaining sub-tasks to close this issue out:
- [x] #181 
- [x] #182 
- [x] #183 
- [x] #184 
- [x] #185

**Comment by jgreben** [comment]
#182 closed by #225

**Comment by jgreben** [comment]
Is #184 closable?

**Comment by jgreben** [comment]
Since #184 was closed, this issue can be closed as well!
