### ISSUE TITLE
Add sul_chrome

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/libsys-webforms#15]

**Comment by jkeck** [comment]
Just as an FYI, `SULStyles` supersedes `SULChrome`.  Not sure if that's what you mean by `sul_chrome` or not, but SULChrome should not be used in modern projects (I'll update the README to reflect that).

**Comment by jgreben** [comment]
No I thought they were different things. Thanks for noticing! I’ll remove this issue. I already have sul_styles added so I’m glad you noticed before I started working on this!
- Josh

On Jan 27, 2016, at 9:46 AM, Jessie Keck <notifications@github.com<mailto:notifications@github.com>> wrote:

Just as an FYI, SULStyles supersedes SULChrome. Not sure if that's what you mean by sul_chrome or not, but SULChrome should not be used in modern projects (I'll update the README to reflect that).
