### ISSUE TITLE
Finish circ_stats management report

### ISSUE THREAD

**Issue by tallenaz** [sul-dlss/libsys-webforms#181]
In PL/SQL, `circ_stats_rpt.request_3_confirm` validates params that `request_4_insert` inserts into the `CIRC_STATS_LOG` table. Does the rails app need to do any additional work? If not, we can close it.

Related to #110

**Comment by matthewahmed** [comment]
The web form basics look to be working right, though in Optional Output the "Show CKEY cells as links to Searchworks" checkbox should be checked by default. If an LDAP lookup for the email address isn't practical, could the email field be filled in with the user's SUNet ID @stanford.edu, which should work 99% of the time?

There are some mistakes in table values. For "LC Letters Range" Type of Selection, entering "A#" in just the first field puts "A#0-9999" in the table's CALL_RANGE column. It should be "A0-9999"

For "Other call numbers", entering "abc" results in "NOT LC/DEWEY:abc". There should be a space after the colon, "NOT LC/DEWEY: abc"

For "Upload a barcode list", the filename on the server should prefix the original filename with the user's SUNet ID and an underscore, but that didn't happen. I uploaded "bcs_for_upload.txt", but on the server it should have been named "mahmed_bcs_for_upload.txt". The table's INPUT_PATH value should include the prefix, but the filename in the CALL_RANGE column should be the original filename (as it is now, no prefix).
