### ISSUE TITLE
Finish shelf selection management report

### ISSUE THREAD

**Issue by tallenaz** [sul-dlss/libsys-webforms#182]
`shelf_sel.request_2_run` kicks off a background script with valid params, and inserts data into the `SHELF_SEL_SEARCHES` table. Does the rails app need to do anything else?

Related to #110

**Comment by matthewahmed** [comment]
The current form has an option to delete criteria entries in SHELF_SEL_SEARCHES (saved by the same user). I don't know if anybody uses that capability. I would include it if it's not much trouble; otherwise wait to see if people ask for it to be restored.

**Comment by tallenaz** [comment]
SHELF_SEL_SEARCHES has composite primary keys (user_name and search_name). Rails doesn't natively support them, so I ran into issues where the app would delete searches that couldn't be distinguished by just one primary key alone. This gem works: https://github.com/composite-primary-keys/composite_primary_keys

**Comment by tallenaz** [comment]
Still need to be able to kick off the report in pl/sql

**Comment by jgreben** [comment]
Will be closed by #225. Matthew still need to set up shelf_sel_rpt.cgi script on symphony.

**Comment by jgreben** [comment]
Closed by #225
