### ISSUE TITLE
Finish expenditures with circ stats report in management reports

### ISSUE THREAD

**Issue by tallenaz** [sul-dlss/libsys-webforms#184]
`request_circ_2_insert` inserts valid params into `EXPENDITURES_CIRC_LOG` table. Anything else the rails app needs to do?

Related to #110

**Comment by matthewahmed** [comment]
That's all it needs to do.

The web form should allow selecting multiple libraries, and default to "All Libraries"

**Comment by tallenaz** [comment]
This report's form lets the user submit without selecting a fund or date range. I'll set it up to act more like the expenditures report.

**Comment by jgreben** [comment]
Is this issue closable?

**Comment by tallenaz** [comment]
Yes!
