### ISSUE TITLE
Add application's connection to Oracle

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/libsys-webforms#20]
And place connection infomation in shared_configs

**Comment by jgreben** [comment]
Install OCI8 gem

**Comment by tallenaz** [comment]
To install the oci8 gem on a mac:

https://coderwall.com/p/nvva7a/setup-oracle-instant-client-and-ruby-oci8-gem-on-mac

if El Capitain:

https://github.com/kubo/ruby-oci8/issues/89

On my macbook, after upgrading to Sienna, and with oracle instant client installed according to the coderwall instructions above, I had to run the `fix_oralib.rb` script in `/usr/local/oracle/product/instantclient_64/lib` and then 

```
$ git clone --depth=1 https://github.com/kubo/ruby-oci8.git
$ cd ruby-oci8
$ gem build ruby-oci8.gemspec    # create a gem file
$ export OCI_DIR=/usr/local/oracle/product/instantclient_64/11.2.0.4.0/lib # set the instant client location
$ gem install ./ruby-oci8-2.2.0.gem
```
