### ISSUE TITLE
Add validation for date_range to endowed_funds report

### ISSUE THREAD

**Issue by tallenaz** [sul-dlss/libsys-webforms#213]

**Comment by tallenaz** [comment]
Does this report write to a db at all?

**Comment by jgreben** [comment]
@tallenaz:  Not directly. It just writes the file of ckeys and submits the cgi request. The cgi script does whatever writing/reading from the db that needs to be done. In PR #224 I added validations for the date ranges and also some methods in the controller concern to make sure there are appropriate date ranges sent to the cgi script.
