### ISSUE TITLE
no default for user_email in batch_update forms

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/libsys-webforms#220]
The user_email column of uni_updates_batch table should NOT be defaulted to SUNetID (or anything else) if the user does not explicitly enter a value in that field on any of the batch_update forms.

So, null value is ok, and in fact, correct, if the field is left blank.  Populating the user_email field in the form with the user's email from webauth is fine.  (See Circulation Statistics Report Request form)

**Comment by jgreben** [comment]
closed by #269
