### ISSUE TITLE
Status column for Sal3_batch_requests_batch has specific values

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/libsys-webforms#238]
Validation should be done on Status column.  Possible values are:
NEW
AUTOAPPROVE
APPROVED
SUSPENDED
REJECTED
INPROCESS
DONE

This status is NOT on creation form, it is set to NEW when a new batch form is submitted.

**Comment by tallenaz** [comment]
When a form is created, status is automatically set to NEW. When in the edit view, there are only a subset of the above to choose from in the dropdown. It's not a rails validation, but the choices the user has are properly restricted.
