### ISSUE TITLE
Status column on edit has short drop down list of choices

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/libsys-webforms#239]
Status column should editable field on the edit form of sal3_batch_requests_batch table. ("Review batches" link)

Display should show current status.

Drop down needed for this column.  Choices in drop down should be
APPROVED
SUSPENDED
REJECTED

**Comment by dlrueda** [comment]
Form not showing these values, or this field as editable.  Perhaps was lost along the way somewhere?

**Comment by jgreben** [comment]
Closed by #284
