### ISSUE TITLE
Fix edit view problem with float ids

### ISSUE THREAD

**Issue by tallenaz** [sul-dlss/libsys-webforms#247]
Links to edit views contain ids:

`sal3_batch_requests_batches/:id/edit`

Because of something going on in the `ruby-oci8/activerecord-oracle_enhanced-adapter` stack, rails saves and displays ids as floats (https://github.com/kubo/ruby-oci8/issues/33):

`sal3_batch_requests_batches/27.0/edit`

which rails doesn't know what to do with, while it does fine with:

`sal3_batch_requests_batches/27/edit`

I see three options for a solution:

1. hack the routes in the app:
`edit_sal3_batch_requests_batches_path(@sal3_batch_requests_batch)` --> `sal3_batch_requests_batches/@sal3_batch_requests_batch.batch_id.to_i/edit`
or some such.
2. try switching out the column type in oracle for the column type the gem expects. Now, the batch_id is a NUMBER, and according to the above issue, the gem wants it to be INTEGER or NUMBER(38).
3. figure out how to configure the gem (https://github.com/kubo/ruby-oci8/issues/33#issuecomment-16273631), but I don't know how to do that in the context of rails.

**Comment by dlrueda** [comment]
I think I'd vote for #2, as long as it's an accepted best practice.  This SAL3 batch requests is not yet in production, no production table, so it's absolutely fine to alter the table right now.
