### ISSUE TITLE
Incorrectly marking some barcodes as duplicates

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/libsys-webforms#249]
Barcodes should be considered duplicates only if the barcode AND date match another barcode-date combination in the uni_updates table.  I think perhaps now just the barcode is being considered a dup?

(I submitted a batch of 23,000 items as the second batch submitted today.  A few thousand were rejected, but none should have been, there were no dups with the only other batch submitted the same day.)

**Comment by jgreben** [comment]
Key does not have to be up to minute, just today's date (YYYYMMDD).
