### ISSUE TITLE
Review stop codes for new sal3 batch

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/libsys-webforms#255]
Not sure if the correct two-letter stopcode is being saved to the table on submit.

Should be
Data Control : DC
Special Collections - Redwood City : RW
Archive of Recorded Sound : DA
Archive of Recorded Sound - Redwood City : RA  (this one is new)
Earth Sciences : DE
Preservation - Book Repair : BR
Green : DS

Labeling as a bug because it is a must have to go to prod with this app.

**Comment by jgreben** [comment]
Closed by #265
