### ISSUE TITLE
Pending should be "Y" when called through rake task

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/libsys-webforms#258]
Calling 'transfer_items' (and maybe the other?) rake tasks creates record in uni_updates_batch table but pending column is null.  Needs to be 'Y'

Pending column for corresponding barcodes in the uni_updates table is 'Y' so that part is working fine.

**Comment by dlrueda** [comment]
Confirming that pending also not set when calling rake task change_home_location

**Comment by jgreben** [comment]
Closed by #266
