### ISSUE TITLE
total_bcs not set during rake tasks

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/libsys-webforms#260]
Calling 'transfer_items' (and maybe the other?) rake tasks creates record in uni_updates_batch table but total_bcs column is null. Needs to be populated.

**Comment by dlrueda** [comment]
Confirming that total_bcs also not set when calling rake task change_home_location

**Comment by dlrueda** [comment]
transfer_items and change_home_location are the ones that most need fixing.  Those are the two that get called now from scripts from the Symphony server.  So, 1st priority to those two.

**Comment by jgreben** [comment]
Closed by #268
