### ISSUE TITLE
Strip empty array object at start of array in management reports for formats

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/libsys-webforms#276]
Is this is a problem for the running of the report? In the circulation_statistics_report, and the expenditures_with_circ_stats, rails adds an empty
Formats: `["", "MANUSCRPT", "MAP", "MARC"]`

This should be done in the models `CirculationStatisticsReportLog` and `ExpendituresWithCircStatsReport`

**Comment by matthewahmed** [comment]
The FORMAT(S) column in both tables works the same as LIBRARIES in [question 278](https://github.com/sul-dlss/libsys-webforms/issues/278) - comma separated list of formats with no quotes, spaces or extra commas. The column in both tables is null if "All Formats" is selected.

**Comment by jgreben** [comment]
Closed by #290
