### ISSUE TITLE
For Circ Stats Report Log, does 'ALL' option need to be 'All Formats'?

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/libsys-webforms#280]
Currently when the report request is submitted the FORMAT field is null. Can/should FORMAT be null?

**Comment by matthewahmed** [comment]
NULL is the correct value in the FORMAT column for "All Formats".

**Comment by jgreben** [comment]
Ok, thanks, then I will close this issue.

**Comment by matthewahmed** [comment]
Now the web form incorrectly sets the FORMAT column to "All Formats". It should be NULL (empty) unless the user chose to limit by format. I meant to refer to the option in the listbox when I said "All Formats"
