### ISSUE TITLE
Should there be an ALL option for Libraries in Circ Stats Report?

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/libsys-webforms#281]

**Comment by matthewahmed** [comment]
No ALL option. "Any lib-loc" goes in the LIBS_LOCS column if the selection is a barcode list, for use in the notification email.

To select all libraries, the LIBS_LOCS column would have a comma separated list of all the library names (w/ or w/o locations), as if the user had multiple-selected all the library names in the libraries listbox. If you keep the "ALL" option, that's how it should go in the table, but it would rarely if ever get used.

**Comment by jgreben** [comment]
Closed by #289
