### ISSUE TITLE
test db connections to oracle

### ISSUE THREAD

**Issue by eefahy** [sul-dlss/libsys-webforms#3]

**Comment by jgreben** [comment]
http://stackoverflow.com/questions/764887/how-to-configure-ruby-on-rails-with-oracle

**Comment by eefahy** [comment]
This might require a firewall rule in place on libdbdev2 (the dev oracle vm)

**Comment by tallenaz** [comment]
libsys-webforms-dev and libdbdev2 are in the same zone, and I added an iptables rule to establish the connection:

```
[azanella@libsys-webforms-dev ~]$ telnet 172.20.207.8 1521
Trying 172.20.207.8...
Connected to 172.20.207.8.
Escape character is '^]'.
```
