### ISSUE TITLE
Shelf selection "Load criteria" adds "All Formats" etc.

### ISSUE THREAD

**Issue by matthewahmed** [sul-dlss/libsys-webforms#300]
If you load saved criteria that limits by format, item type and/or item categoroy1, the corresponding listboxes have "All whatever" also selected along with whatever was specified in the criteria. You can see by loading the saved "Green Stacks E limit by Format etc mahmed"

**Comment by matthewahmed** [comment]
This was working OK, but now it's back, adding "All whatever" to the actual saved formats etc. Maybe the fix for saved "All whatevers" not getting selected https://github.com/sul-dlss/libsys-webforms/issues/345 undid this fix

**Comment by jgreben** [comment]
Closed by #360
