### ISSUE TITLE
Expenditures request has no effect?

### ISSUE THREAD

**Issue by matthewahmed** [sul-dlss/libsys-webforms#304]
When I request an Expenditures report in the web form,  it no longer creates a row for that request in the EXPENDITURES_LOG. That was working in the past.

**Comment by jgreben** [comment]
@matthewahmed when did it work last? How long ago in the past?

**Comment by jgreben** [comment]
@matthewahmed Also, when did you test this? libdbdev2 was down for a little while today...

**Comment by matthewahmed** [comment]
I was mistaken, the row was created. But there is a lesser problem which faked me out. The DATE_REQUEST value has just the truncated date (as you might presume from the column name), but ideally it should also include the time to help any investigation.

When I refreshed table sorted by DATE_REQUEST desc, I didn't see a new row at the top, because its truncated date was sorted below my earlier comparison request from the PL/SQL form, which includes the time.
