### ISSUE TITLE
Expenditures (& with Circ) and Encumbrances have LAW funds

### ISSUE THREAD

**Issue by matthewahmed** [sul-dlss/libsys-webforms#306]
The Fund selection controls include LAW funds. They should only have SUL funds.

I think the funds list is obtained from the EXPENDITURES_FUNDS table. It can be limited to SUL funds with:
`and inv_lib = 'SUL'`
(Years ago we planned to add LAW to expenditures reports, but I guess dropped it because they didn't need it.)

**Comment by jgreben** [comment]
Closed by #314
