### ISSUE TITLE
Encumbrances report needs to run immediately

### ISSUE THREAD

**Issue by matthewahmed** [sul-dlss/libsys-webforms#309]
The same issue came up for the Expenditures report, and Josh found a way to start the PL/SQL procedure after putting the request specifications in the table.
I don't remember how that worked but hopefully the same approach would work here. I'll need to help with the PL/SQL details. The procedure to run is ENCUMB_RPT.RunSchedRpt.

**Comment by jgreben** [comment]
Closed by #335
