### ISSUE TITLE
Create apache directory rules for various webform access

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/libsys-webforms#31]
See #30 for the different webforms

**Comment by dlrueda** [comment]
SUNetIDs for Batch record updates:
dlrueda
vtang
mahmed
ahafele
rlunnon
azanella
jgreben

SUNetIDs for Sal3 Batch Requests
dlrueda
pernell
seestone
rdsadler
ptwiss
azanella
jgreben
rlunnon

SUNetIDs for Management Reports
krisk11 
ronbo  
winklerh
amlevia  
qqiu  
dkohnke 
tnoakes 
konjevic
ezalite 
qingxia 
yinghuo 
seikof  
ihhae3  
hyun1  
mmarosti
wcao9971
scaneda 
jgreben 
barghi  
miekom  
zhxue  
rnanders
fkotas  
cmatson 
kyungmic
bp2003  
dlrueda 
slash  
nrz  
vtang  
mahmed  
snydman 
linchang
raynbow 
liisie  
regirob 
nismoser
oderosa 
amorgan2
mako  
seestone
tofa  
angetsai
laszloj 
reganmk 
celone  
graceb  
griego  
jeilts  
jmustain
juliets 
karenf  
kkerns  
lowood  
mnewman 
mtashiro
phthomas
pzarins 
rawlings
rondest 
skota  
ssussman
trujillo
zbaker  
mnack  
shorsfal
findleyn
jlmcbrid
bstone  
terwin  
chang74 
cannie  
pernell 
raymondh
jkeck  
cfosselm
helenj  
nauerbac
gworthey
lmcrae  
ppb  
mcalter 
eoh  
jrjacobs
slester 
kgust  
afishaut
jdyang  
sonialee
dajordan
amanheim
dhartwig
clandry 
hettelj 
rns  
thalassa
bess  
ahafele 
crperks 
rlunnon 
kcadena 
rcviado 
ksmith11
wingfiel
sforzett
gsalim  
kteel
azanella

**Comment by jgreben** [comment]
An example of an apache conf. entry would look something like this:

```
<Directory /opt/app/libsys/libsys-webforms/current/ >
    AuthType WebAuth
    require user jgreben jmorley dlrueda mahmed azanella
    Order deny,allow
    Deny from all
    Satisfy any
  </Directory>
```

**Comment by jgreben** [comment]
Can we use an external file (not puppetized) for the 'require user' list? .htaccess maybe?

**Comment by tallenaz** [comment]
https://github.com/sul-dlss/puppet/commit/de05f9a19b2fd95f4091c0c02512aff1ee6109f3
