### ISSUE TITLE
Endowed Funds report selection ignores date range

### ISSUE THREAD

**Issue by matthewahmed** [sul-dlss/libsys-webforms#310]
The web form writes a ckey list used by endow_rpt.cgi. The ckey list contained all the ckeys for the requested fund(s) in the EXPENDITURES table, instead of limiting by the date range specified in the web form.

**Comment by jgreben** [comment]
@matthewahmed can you clarify which date column in the EXPENDITURES table corresponds to each date selection in the endowed_funds_report form? The columns I see in the table are ROW_DATE, REVIEW_DATE, TA_DATE_2ENCINA, TA_VEND_INV_DATE, TS_DATE_MAILED, OR_CREATE_DATE, and TO_ORDER_LINE_CRE_DATE. There's also a TI_FISCAL_CYCLE String. 

Basically to fix this I need to construct an SQL query  `SELECT TA_FUND_CODE from EXPENDITURES where TA_FUND_CODE like ? and ...`

I assume I will need a different `and ...` condition depending on the date range type that was selected.

**Comment by jgreben** [comment]
Use TI_FISCAL_CYCLE for FY
Use TA_DATE_2ENCINA for Cal and PD
