### ISSUE TITLE
Shelf Selection "Load criteria" missing values

### ISSUE THREAD

**Issue by matthewahmed** [sul-dlss/libsys-webforms#315]
When "ART all criteria non-default (mahmed)" is loaded, these controls were left at defaults:

- "Exclude items with Current Location different from Home Location" should be checked.
- "Type of Call Number selection to use in the report" should be changed to "Classic Selection",
and accordingly three call number input fields should be shown.
- "Exclude Bound-With Child items" should be unchecked
- Bottom radio button "Use as email subject only, don't save" should be selected.

If I missed or misstated any differences with http://sulohsdev1.stanford.edu/morison/batch/shelf_sel.request, those should be the same too.

**Comment by jgreben** [comment]
The first three bullet points were cause by a javascript bug (fixed in a previous PR). The only change needed now is: 
• Bottom radio button "Use as email subject only, don't save" should be selected.

**Comment by jgreben** [comment]
Closed by #322 and #324
