### ISSUE TITLE
Do final steps to move app to production

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/libsys-webforms#319]
Before cutover day:
- [x] Mount point for bodoni/libsys-webforms-prod
- [x] Waiting on UIT
- [x] Tony: deploy puppet code

On day we cut over to prod:
- [x] Josh: Deploy latest master to production
- [x] Darsi: create sal3_batch_requests tables on LTRXPRD1
- [x] Darsi: create Sequences on LTRXPRD1
     - 	Uni_updates_batch.batch_id
     - 	Sal3_batch_requests_batch.batch_id
- [x] MFA put new scripts to bodoni cgi-bin/webforms
- [x] MFA decommission only UNICORN_UPDATES package
- [x] DLR put new UNI_UPDATE package to LTRXPRD1
- [x] DLR move three scripts to prod to start using rake tasks (new libsys-webforms)
    -  	Las_accession
    -  	Green_southstks
- [x] DLR: When scripts run smoothly, announce new libsys-webforms site to all users
- [x] MFA decommission/whatever old ohsprod mgt report packages

**Comment by dlrueda** [comment]
For sequences:

sys@LTRXDEV1> select max (batch_id) from ora_sul.sal3_batch_requests_batch ;
MAX(BATCH_ID)
-------------
Elapsed: 00:00:00.03
sys@LTRXDEV1> select batch_id from ora_sul.sal3_batch_requests_batch ;
no rows selected
Elapsed: 00:00:00.00
sys@LTRXDEV1> create sequence ora_sul.sal3_batch_requests_batch_seq ;
Sequence created.
Elapsed: 00:00:00.11


sys@LTRXDEV1> select max (batch_id) from ora_sul.uni_updates_batch ;
MAX(BATCH_ID)
-------------
15190
Elapsed: 00:00:00.01
sys@LTRXDEV1> create sequence ora_sul.uni_updates_batch_seq start with 15191 ;
Sequence created.
Elapsed: 00:00:00.06

**Comment by matthewahmed** [comment]
The sequence names in LTRXDEV1 are SAL3_BATCH_REQUESTS_BATCH_SEQ, UNI_UPDATES_BATCH_SEQ. I take it the above means they should they be set to one more than the MAX(BATCH_ID) at the time of the switch over.

I've copied the updated EXPEND_RPT and ENCUMB_RPT packages to LTRXPRD1, with the procedures to schedule reports to run immediately. The current reports still work with this.

**Comment by dlrueda** [comment]
No, once sequences are made on the uni_updates_bat_seq especially, the old code will break, including calling it from a couple of automated scripts that run daily.

We need to make the sequences at the same time I put three updated scripts into place, and some pl/sql code into place.
