### ISSUE TITLE
Update column headers for management report forms

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/libsys-webforms#329]
Instead of column names 
![screen shot 2017-01-25 at 3 44 28 pm](https://cloud.githubusercontent.com/assets/14914677/22314186/2d46fac4-e315-11e6-82e9-6e2de6406abc.png)

make them "First payment date" and "Last payment date"

**Comment by jgreben** [comment]
Closed by #337

**Comment by jgreben** [comment]
Closed by #332
