### ISSUE TITLE
Duplicate file names from Back button

### ISSUE THREAD

**Issue by matthewahmed** [sul-dlss/libsys-webforms#331]
I requested an Encumbrances report limited to "$0 paid", then I used the back button to just change it to "More than $0 paid" for the same fund. Both reports had the same OUTPUT_FILE name in the ENCUMBRANCES table, so one of the reports would be overwritten by the other.

Apparently the output file name is derived from the time that the web form first loaded. Any other reports that generate filenames the same way will have the same vulnerability.

If the file name was based on the time after the Submit button is pressed, the duplicates would be avoided. I expect using the Back button will be rare, but it will happen when someone wants to request another report keeping most of the settings from the just requested report.

**Comment by jgreben** [comment]
Closed by #333
