### ISSUE TITLE
Fix Shelf Selection error saving criteria

### ISSUE THREAD

**Issue by matthewahmed** [sul-dlss/libsys-webforms#356]
If you choose save selection criteria, there's an error message like this:

ActiveRecord::RecordNotFound in ShelfSelectionReportsController#create
Couldn't find all ShelfSelSearches with 'user_name,search_name': (mahmed, New ART A) (found 0 results, but was looking for 1)

with this line highlighted:
ShelfSelSearch.find(find_array).update(params)

**Comment by matthewahmed** [comment]
This still happens regardless whether there's a comma in the Save name

**Comment by jgreben** [comment]
Fixed by #357
