### ISSUE TITLE
Add page(s) for Accession Number Generator

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/libsys-webforms#373]
Need details for what this should be from Matthew.  After adding some details, you could unassign yourself.

I would vote for changing user access to authorized_user table for this, since that's how all the others work.

**Comment by matthewahmed** [comment]
How about I write Consul page with the requirements? I think that would be more coherent than in github comments.

On switching user access to authorized_user, I suggest first enabling specified non-Systems users to add authorized_user entries. I used a SUNet ID list file so Vitus and Joanna could add users without bothering Systems.

There's one table CATNUMS with a row for the last used value of each call-number sequence:
[http://sulohsdev1.stanford.edu/morison/batch/catnum_admin.display](http://sulohsdev1.stanford.edu/morison/batch/catnum_admin.display)

There are 5 different pages for getting the next call number for a particular sequence, e.g. "ZDVD 34212" where 34212 is the sequence number, and incrementing that sequence in the table. The procedure currently updates the sequence number with an SQL table update, not with a trigger or SQL sequence.

The users care a lot about the layout and wording of the pages. There are a few people (Later I need to find who they are in old email) who should be consulted about any changes.

**Comment by matthewahmed** [comment]
I wrote a Consul page that has everything relevant that I can think of:
[https://consul.stanford.edu/display/SYSTEMS/Accession+Number+Generator](https://consul.stanford.edu/display/SYSTEMS/Accession+Number+Generator)

I didn't know where this should fit in the Systems Consul space, so currently that doesn't have any link to the page.
