### ISSUE TITLE
Endowed Funds Report ckey list always empty

### ISSUE THREAD

**Issue by matthewahmed** [sul-dlss/libsys-webforms#379]
The webform writes a list of ckeys from the EXPENDITURES table rows matched. Now the ckey list is always one byte, just a newline character. It doesn't matter what kind of date range is selected.

**Comment by jgreben** [comment]
Fixed by #381

**Comment by jgreben** [comment]
Closed by #381

**Comment by jgreben** [comment]
@matthewahmed Thanks, this should be fixed now.
