### ISSUE TITLE
Endowed Funds Report - tell user if search found no matches

### ISSUE THREAD

**Issue by matthewahmed** [sul-dlss/libsys-webforms#383]
If the user's selected fund(s) and date range doesn't match any ckeys, the web page should tell the user instead of generating an empty report. One possible method is checking if a non-empty ckey list got created (and not just a newline).

For testing on Morison, the webforms request should get the same report as the old PL/SQL version:
[http://sulohsdev1.stanford.edu/morison/batch/expend_rpt.request_endow](http://sulohsdev1.stanford.edu/morison/batch/expend_rpt.request_endow)

**Comment by jgreben** [comment]
This is fixed. Can't find the closed PR though..
