### ISSUE TITLE
Page needed for digital-bookplates, with ckey file

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/libsys-webforms#385]
Page to add a 979 to a set of ckeys.
File of ckeys would be uploaded.

979 would be added to all ckeys.

There would be a record created via Argo.  So perhaps the form would accept 1. ckey file and 2. druid (or whatever identifier makes sense)

**Comment by shelleydoljack** [comment]
The symp_dor.txt file contains all the 979 metadata we'd add to a record. It includes lines for bookplates that do not have an associated Symphony fund:
`ch860sp7730	druid:ch860sp7730	ch860sp7730_00_0001.jp2	Gift of George F. Shaner, Esq.`

We should use this file to populate a selection list for adding data to a file of ckeys.

**Comment by shelleydoljack** [comment]
Documentation on general workflow under the section Phase 2 at https://consul.stanford.edu/x/n4orCQ .
