### ISSUE TITLE
Deal with multiple email addresses in uni batch updates form

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/libsys-webforms#390]
Not sure if this can/should be used for ALL forms, but at least for the uni batch updates form.

User wants to send email out to multiple addresses.  Wants to format like so:
email1, email2 (with space in-between)

Email does NOT go out, and email for 1st address seemed to be truncated to username only, @stanford.edu got dropped.  "vtang" only was entered in the uni_updates_batch table.

**Comment by dlrueda** [comment]
Recommend stripping out spaces in emails.

Could also verify format of emails, i.e., username@domain.blah
but still needs to allow multiples.  Could validate each one.

I'm not that concerned about format.  If they screw it up, they don't get the email, too bad.  But it would be nice to accept multiple emails when formatted correctly.  A "comma space" between emails seems reasonable.

**Comment by jgreben** [comment]
It's the libsys-webforms Rails mailer that is not sending out the emails correctly.

**Comment by dlrueda** [comment]
Also fails (in same way), if "email1@domain.com,email2@domain.com" is entered without a space in between.

**Comment by dlrueda** [comment]
This is what email header looks like that I received (as a member of sul-unicorn-devs@lists).  
![screen shot 2017-05-11 at 4 58 26 pm](https://cloud.githubusercontent.com/assets/14914677/25976638/1197b620-366b-11e7-992c-1ffaca8f36bd.png)

Turns the email entered into vtang@libsys-webforms-prod.stanford.edu.
Enters vtang into the uni_updates_batch table.

**Comment by dlrueda** [comment]
User still reports a problem when entering emails in "email1, email2" format (comma and space between emails). 

Issue is not closed so not sure if this is still in progress or was supposed to have been fixed.

**Comment by dlrueda** [comment]
Would be helpful to have small text explaining correct format for multiple emails on the form.

**Comment by jgreben** [comment]
Closed by #432
