### ISSUE TITLE
investigate rails connections to pre existing oracle db

### ISSUE THREAD

**Issue by eefahy** [sul-dlss/libsys-webforms#4]

**Comment by jgreben** [comment]
Installing ruby-oci8:
http://www.rubydoc.info/gems/ruby-oci8/2.2.0/file/docs/install-full-client.md

Some of this work will need to be done on the server (setting the correct LD_LIBRARY_PATH).

**Comment by jgreben** [comment]
General ruby-oci8 class documentation: http://www.rubydoc.info/gems/ruby-oci8/2.2.0
