### ISSUE TITLE
Create a rake task and cap deploy hook for placing the xform-marc21-to-xml.jar

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/libsys-webforms#400]
Currently we have to manually do

`[libsys@libsys-webforms-dev ~]$ cp xform-marc21-to-xml-jar-with-dependencies.jar libsys-webforms/current/lib/`

whenever there is a deploy

**Comment by shelleydoljack** [comment]
I think this was fixed in #429

**Comment by jgreben** [comment]
:+1
