### ISSUE TITLE
Update fiscal year selection to use FY column for endowed funds

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/libsys-webforms#401]
Refactor code so that when a user selects the fiscal year option in the endowed funds report, the selection against the table looks for rows with the FY specified in the form, instead of doing a date selection.

This will be especially helpful because, although our FY is Sept-Aug, the dates for the FY are not always exactly Sept 1 - Aug 31.  If rollover was done earlier in August (as often is the case), then there COULD be some orders/payments with Aug dates that are in the NEXT fiscal year.

**Comment by dlrueda** [comment]
This behavior (selecting on FY from tables when FY selected in form) should happen for all forms with FY selection option.  (e.g. Expenditure reports)

**Comment by jgreben** [comment]
Something like:
```
Expenditures.where("ta_fund_code = ? AND ti_fiscal_year > ? AND ti_fiscal_year < ?, fc, date_start, date_end).pluck(:ol_cat_key)
```

i.e. it should include all the intervening years between date_start and date_end.

**Comment by jgreben** [comment]
Blocked by https://github.com/sul-dlss/LibSysTasks/issues/270
