### ISSUE TITLE
Email sal3contact@stanford.edu when sal3 batch request submitted

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/libsys-webforms#456]
When a new Sal3 batch request form is submitted, an email should be sent to:
sul-unicorn-devs@lists.stanford.edu
sal3contact@stanford.edu
whatever email was entered in submitted form

This should happen for both development and production environments (don't need for test)

**Comment by dlrueda** [comment]
re-opening this ticket.  I believe the email was added to the wrong libsys-webforms form, specifically it got added to the   def batch_upload_email(uni_updates_batch, duplicates)

So instead of sending when uni_updates_batch, I think we need a new and separate def for sal3_batch_upload_email (or named whatever, just for a SAL3 batch request submission).

**Comment by jgreben** [comment]
Fixed by #467
