### ISSUE TITLE
Check paid_date query for endowed funds report

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/libsys-webforms#460]
On dev there should be keys for:

ALL SUL FUNDS
paid_date Sept 6 2013

**Comment by rlunnon** [comment]
Dev:  bad dates? should be 2012:  selected pay date 07-Sep-12 to 19-Dec-12; header on report:
Expenditures Report (brief)  Fund: 1065083-101-  Date range:  07-Sep-0012 to 19-Dec-0012  Report created: 22-FEB-18 14:35

**Comment by rlunnon** [comment]
Second example bad dates:
Expenditures Report  Fund: 1065083-101-KATDJ  Date range:  30-Aug-0013 to 11-Oct-0013  Report created: 22-FEB-18 12:52
