### ISSUE TITLE
Refine sort order for digital bookplates batch

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/libsys-webforms#495]

**Comment by shelleydoljack** [comment]
The batch ID in the queue and completed views doesn't sort numerically, e.g. 11, 10, 9, but rather ascii-ly, e.g. 10, 11, 1, 2, 3.

**Comment by jgreben** [comment]
The sort order in production looks fine. Maybe it wasn't using datatables before and datatables fixes it?

![screen shot 2018-09-04 at 11 33 01 am](https://user-images.githubusercontent.com/3093850/45050584-84f26200-b036-11e8-8090-9579542e7b58.png)

![screen shot 2018-09-04 at 11 33 13 am](https://user-images.githubusercontent.com/3093850/45050587-87ed5280-b036-11e8-9632-3b93fd63cd1d.png)
