### ISSUE TITLE
Start date blank when open edit batch page

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/libsys-webforms#502]
For SAL3 batch requests, when click on "manage batch" the start date is not displaying (not being pulled correctly from the table?)

When the user saves the data (i.e. to update the status), the start date then saves as blank into the table.

**Comment by dlrueda** [comment]
I can't replicate this problem.  Will see if it's reported again.  Until then, no action required.

**Comment by dlrueda** [comment]
@jgreben I think this was browser specific, and I think you fixed it already?  If so, close...

**Comment by jgreben** [comment]
Fixed by #503
