### ISSUE TITLE
Add sal3_batch_requests_bcs view

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/libsys-webforms#504]
From "batch details" page in libsys-webforms/sal3-batch-requests

Have a button "View barcodes"

That page will show minimal batch summary at top (populated from sal3_batch_requests_batch table values):
batch_name, status, batch_startdate, batch_needbydate, stopcode, pseudo_id, num_bcs

Then have table of sal3_batch_requests_bcs, all entries for this batch. Columns to display:
item_id, pull_date (labeled Request-to-pull Date), completed_date (labeled Retrieval Date)

**Comment by jgreben** [comment]
Completed by #507
