### ISSUE TITLE
Assess Upgrading Libsys-Webforms to Rails 5.2

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/libsys-webforms#509]
Rails 5.2 gives us ActiveStorage and other new things. Relates to #508

**Comment by shelleydoljack** [comment]
Current plan is to update to rails 5.0 then go to 5.2. For 4.2 > 5.0 we have to do something regarding the Oracle table columns that are datatype `DATE` (see https://github.com/rsim/oracle-enhanced#upgrade-rails-42-or-older-version-to-rails-5). Our ActiveRecord models that correspond to these columns are of datatype `:datetime`.  In Rails 5, these are now handled as `:date`, which I think will be just YY-MM-DD format. The recommendation is to update the datatypes for these columns to Oracle datatype `TIMESTAMP`. If we do not want to update our Oracle datatypes, some other possible solutions can be found here: https://github.com/rsim/oracle-enhanced/issues/1679 .

**Comment by shelleydoljack** [comment]
We decided to investigate an approach on the Rails app side instead of upgrading our Oracle schema. See the referenced oracle-enhanced issue for possibilities.

**Comment by shelleydoljack** [comment]
On our way!! #610 merged and deployed.

**Comment by jgreben** [comment]
Upgrade to 5.2 fixed by https://github.com/sul-dlss/libsys-webforms/pull/621

**Comment by shelleydoljack** [comment]
Closed by #627
