### ISSUE TITLE
Build "view errors" for edi management

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/libsys-webforms#511]
Page will display entries in table edi_error_report.  
Investigate possible options to limit display by date, or by date/time.

Usual sorting ability by clicking on column header.

Users will get to view errors page in 2 ways:

1. Choose the option "view errors" in libsys-webforms, and put in a date (and time??) 
Should then view all errors for that date (and that time or later?)
Or put in both start time and end time, and return all lines in the table between those times?

2. When edi processing runs, users get an email with a URL

old form URL: http://sulohsprod1.stanford.edu/library/batch/EDI_ERROR.display_error?p_date_time=19-apr-2017%2009:16:00&p_end_time=19-apr-2017%2009:16:08&p_range=ALL&p_level=notify

new form URL should be similar to this (for the batch updates errors):
https://libsys-webforms.stanford.edu/batch_record_updates/errors_for_batch?utf8=✓&batch_number=28901&commit=Go

The old form URL (and PL/SQL procedure it calls) shows errors between p_date_time and p_end_time (this is start and end time for the edi_processing run that generated the URL, i.e., user sees errors only for the one processing run).

It would be nice to be able to replicate the "show the errors for one processing run" by sending in a start and end time to a libsys-webforms URL, as well as the date to display.

**Comment by dlrueda** [comment]
MVP:
1. Show all errors in table for a date.
2. Restrict access to those in edi_inv_manage column of authorized_user table.
3. Get to show errors page through libsys-webforms OR clicking on URL from an email.

**Comment by jgreben** [comment]
Fixed by #522
