### ISSUE TITLE
Build view invoices page for libsys-webforms 

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/libsys-webforms#513]
Display edi_invoice table

**Columns to display are**
edi_doc_num  (column header should be Invoice Number)
edi_vend_id (column header: Vendor ID)
edi_vend_inv_date (column header: Vendor Invoice Date)
todo (column header: Status)
uni_inv_cre_date (column header: Symphony Invoice Date Created)
edi_total_pieces (column header: Total Pieces)

**One filter needed:**
column: edi_vend_id (Vendor ID)
Code should determine what the different values are in this column of the edi_invoice table, then display a drop down to be able to filter on and display only a specific vendor

**Comment by jgreben** [comment]
Fixed by #517
