### ISSUE TITLE
Allow user to set invoice to 'Excld' in edi_invoice table

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/libsys-webforms#515]
User has chosen "Exclude an invoice" .....

user enters two values to identify invoice to exclude:
invoice number (edi_doc_num in edi_invoice table)
vendor ID (edi_vend_id in edi_invoice table)

**If this edi_doc_num and edi_vend_id combination DOES NOT EXIST in edi_invoice**
Insert a row with this edi_doc_num and edi_vend_id, setting todo = 'Excld'
(see next comment for INSERT statement currently used)

**If this edi_doc_num and edi_vend_id combination EXISTS in edi_invoice**
1.
validate the todo field for this invoice.  Needs to be:
NULL, 'CreInvc', 'SKIP', 'CreOrd', 'Excld'

If not one of those values, return error message to user:
Flash message : "Invoice NOT excluded"
Error message that remains on screen:
"This invoice already through edi processing past point of safe Exclusion through web form."

2.
If passes todo check in 1....
2a. update edi_invoice table to wipe out most values for this line, and set todo = 'Excld'
     (see below comment for UPDATE statement currently used)

2b. remove any lines for this edi_doc_num and edi_vend_id combination in edi_inv_line and edi_inv_piece tables 
     (see below comment for DELETE statements currently used)

**Comment by dlrueda** [comment]
If edi_doc_num and edi_vend_id combo does not exist in edi_invoice table, insert a row with todo= ‘Excld’

```
INSERT INTO edi_invoice
      ( edi_vend_id,
        edi_msg_id,
        edi_msg_typ,
        edi_doc_num,
        todo,
        edi_msg_seg )
     VALUES
      ( p_edi_vend_id,
        'Excld',
        'INVOIC',
        p_edi_doc_num,
        'Excld',
        'HDR' );
```

**Comment by dlrueda** [comment]
edi_doc_num and edi_vend_id combo DOES exist already in edi_invoice table:
update the edi_invoice table for this invoice, wiping out most entries, update todo=’Excld’

    UPDATE edi_invoice SET
    todo                = 'Excld',
    uni_vend_key        = NULL,
    uni_accrue_or_pay_tax = NULL,
    edi_stanfd_account  = NULL,
    uni_inv_lib         = NULL,
    uni_inv_key         = NULL,
    uni_inv_num         = v_uni_inv_num    || '<-Excld',
    edi_invc_total      = 0,
    uni_invc_total      = 0,
    edi_total_postage   = 0,
    edi_total_freight   = 0,
    edi_total_handling  = 0,
    edi_total_insurance = 0,
    edi_cur_code        = NULL,
    edi_total_tax       = 0,
    edi_exchg_rate      = NULL,
    edi_tax_rate        = NULL,
    edi_total_pieces    = 0
    WHERE  edi_doc_num  = p_edi_doc_num
    AND    edi_vend_id  = p_edi_vend_id;

**Comment by dlrueda** [comment]
remove all the lines that might be in edi_inv_line and edi_inv_piece table for this invoice
```
   DELETE edi_inv_line
    WHERE  edi_doc_num  = p_edi_doc_num
    AND    edi_vend_id  = p_edi_vend_id;

    DELETE edi_inv_piece
    WHERE  edi_doc_num  = p_edi_doc_num
    AND    edi_vend_id  = p_edi_vend_id;
```

**Comment by jgreben** [comment]
Fixed by https://github.com/sul-dlss/libsys-webforms/pull/535

**Comment by dlrueda** [comment]
Acceptance criteria:

- [x] Adds new line to edi_invoice with todo=Excld if doesn't exist
- [x] Updates line in edi_invoice to todo=Excld if does exist
- [x] Removes lines in edi_inv_line table if exists in edi_invoice table
- [x] Removes lines in edi_inv_piece table if exists in edi_invoice table
- [x] Rejects update to Excld if todo not in list of OK values
