### ISSUE TITLE
Allow user to update various fields in edi_inv_line table

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/libsys-webforms#516]
User has chosen "Change invoice line" ......

User enters three values to identify invoice line to review and update:
invoice number (edi_doc_num in edi_inv_line table)
vendor ID (edi_vend_id in edi_inv_line table)
invoice line number (edi_line_num in edi_inv_line table)

Display multiple fields from edi_inv_line table for correct invoice line.  Some fields will be editable.  (Next comment for details)

User can update editable values and submit to update values.

**Comment by dlrueda** [comment]
Fields to display from edi_inv_line table:

edi_vend_id (label: Vendor)
edi_doc_num (label: Invoice Num)
edi_line_num (label: Line Num)
edi_fund (label: Fund Name)
edi_po_number (label: PO Number)
edi_line_net (label: Net Amount)
edi_line_gross (label: Gross Amount)

**Comment by dlrueda** [comment]
Fields that are editable

edi_fund (label = Fund Name)  -- this is a required field, blank on submission is error
edi_po_number (label = PO Number)   -- NOT a required field, can be blank (or blanked out during edit)

**Comment by jgreben** [comment]
Fixed by #532
