### ISSUE TITLE
Fix error key not found: edi_inv_view

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/libsys-webforms#519]
Getting error when try to administer users in libsys-webforms-dev
key not found: "edi_inv_view"

![screen shot 2018-06-28 at 12 29 50 pm](https://user-images.githubusercontent.com/14914677/42056462-264cad42-7acf-11e8-9697-3f84be2b51ac.png)

**Comment by jgreben** [comment]
Fixed by #522

**Comment by jgreben** [comment]
Waiting for this to be deployed to prod.

**Comment by jgreben** [comment]
this is deployed now
