### ISSUE TITLE
Batch Record Updates: query and display uni_updates_errors table for a batch_id

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/libsys-webforms#52]

**Comment by jgreben** [comment]
"Enter a batch id:"

<img width="372" alt="screen shot 2016-03-28 at 2 45 37 pm" src="https://cloud.githubusercontent.com/assets/3093850/14091211/c441505c-f4f3-11e5-8742-12eaa9fd673f.png">

http://sulohsprod1.stanford.edu/library/batch/unicorn_updates.show_errors?p_batch=21825
2 queries: (1 header) UNI_UPDATES_BATCH and (2 table) UNI_UPDATES_ERRORS
