### ISSUE TITLE
Update title on "view invoices" page

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/libsys-webforms#520]
Update title of "view invoices" page to 
EDIFACT invoices

**Comment by jgreben** [comment]
Fixed by #522

**Comment by dlrueda** [comment]
Sorry, I think I was unclear.  A couple of screen shots will be helpful:

On this page, I want the choice to view invoices to say "View invoices"
![screen shot 2018-07-02 at 2 37 42 pm](https://user-images.githubusercontent.com/14914677/42187622-888b8b7a-7e05-11e8-8afe-9725f233c9e5.png)

**Comment by dlrueda** [comment]
And on the page that actually shows the invoice, the title/header for the page should be "EDIFACT invoices"  (instead of the currently showing "EDIFACT invoice management"

![screen shot 2018-07-02 at 2 39 20 pm](https://user-images.githubusercontent.com/14914677/42187677-baebc9f4-7e05-11e8-887b-4a94a5798268.png)

**Comment by jgreben** [comment]
Fixed by #522
