### ISSUE TITLE
set up Symws for search

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/libsys-webforms#527]

**Comment by dlrueda** [comment]
James Jacobs wants to use 
http://XXXXXXX:XXXX/symws/rest/standard/searchCatalog?clientID=XXXXXXXXXX&term1={ISBN}
  
We should set up a login that has access to searchCatalog but nothing else.  No updates!

**Comment by dlrueda** [comment]
Hi Darsi,
  
I've installed some software called JTACQ (http://www.jtdata.com/jtacq.html) to help me do catalog checking (Krisk and I receive a LOT of spreadsheets of govt docs discarded from other libraries). Jtacq will take a spreadsheet of titles and run a search or our local catalog and tell me which ones we do and don't have. Very handy.
  
However, in order for the system to run, it needs a couple of pieces of Sirsi information. Are you able to share with me the IP address/port and client ID for the catalog?
  
http://XXXXXXX:XXXX/symws/rest/standard/searchCatalog?clientID=XXXXXXXXXX&term1={ISBN}
  
Thanks for the help.
  
best,
  
james

**Comment by jgreben** [comment]
Closing and moving to https://github.com/sul-dlss/LibSysTasks/issues/346
