### ISSUE TITLE
Allow user to update barcode_num field in edi_lin table (deal with duplicate barcodes)

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/libsys-webforms#529]
User has chosen "Fix duplicate barcode" from EDIFACT invoice management menu.

User enters the barcode that is the duplicate.

Find and display lines in edi_lin table with barcode_num = duplicate barcode entered. (SQL in comment below.) Fields to display:
vend_id (label = Vendor)
doc_num (label = Invoice Num)
edi_lin_num (label = Line Num)
barcode_num (label = Barcode)

There should be at least 2 lines in edi_lin table to display.  If zero lines match this barcode_num, display error "No lines in edi_lin table with that barcode number."  If only one line matches this barcode_num, display error "This barcode is not a duplicate.  It only appears once in edi_lin table."

User chooses which invoice line to update, then can update the edi_lin.barcode_num field for that line.   edi_lin table is updated (SQL in comment below).

**Comment by dlrueda** [comment]
SQL to identify lines in edi_lin table that match the duplicate barcode entered by the user

SELECT vend_id, doc_num, edi_lin_num, edi_sublin_count, barcode_num 
FROM edi_lin
WHERE barcode_num = _barcode entered by user_

**Comment by dlrueda** [comment]
SQL to update edi_lin table 

UPDATE edi_lin
SET barcode_num = _new barcode value entered by user_
WHERE vend_id = p_vend_id
AND doc_num = p_doc_num
AND edi_lin_num = p_edi_lin_num
AND edi_sublin_count = p_edi_sublin_count
AND barcode_num = p_old_barcode_value

**Comment by jgreben** [comment]
Ned to set up a sequence number and table column for edi_lin.

**Comment by jgreben** [comment]
Fixed by https://github.com/sul-dlss/libsys-webforms/pull/535

**Comment by jgreben** [comment]
We are already using the `composite_primary_keys` gem, so this can proceed...

**Comment by jgreben** [comment]
Fixed by #548
