### ISSUE TITLE
Add location for EARTH-SCI to mgt rpts

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/libsys-webforms#582]
I am trying to run a shelf selection report on my “ATCIRCDESK” items, but that location is not in the dropdown menu for the EARTH-SCI library. Can that be added?

I believe these are loaded to webforms from a table?

**Comment by dlrueda** [comment]
Aha, it IS a table update only. UNI_LIBS_LOCS.
I added EARTH-SCI/ATCIRCDESK to both LTRXDEV2 and LTRXPRD1

**Comment by dlrueda** [comment]
I guess I have a question about whether any libsys-webforms tests will fail because of adding this lib/loc to the table.  Not sure about that, and would like Shelley to double-check.

**Comment by shelleydoljack** [comment]
No, it won't break any tests. We can add the location to https://github.com/sul-dlss/libsys-webforms/blob/master/spec/fixtures/files/uni_libs_locs.csv but I don't see any tests for shelf reports that searched for anything in EARTH-SCI or ATCIRCDESK locations so it would be kind of pointless to add it without adding a test for it.

**Comment by dlrueda** [comment]
Let's not add it, I don't think that csv file is, or needs to be complete.
