### ISSUE TITLE
Public view of the Eloader webforms

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/libsys-webforms#583]
I would like to be able to give acquisitions (maybe others - it could be open to all) access to view eloader packages using the webform admin. But I do not want them to be able to do anything other than view the list of packages and the package details.

**Comment by shelleydoljack** [comment]
Should they be able to view the FTP login information?

**Comment by ahafele** [comment]
hmm. Acquisitions yes, that is fine. If it is made broadly public then no.

**Comment by shelleydoljack** [comment]
For the details page, the public view should exclude the pickup information (AFS and FTP info).
