### ISSUE TITLE
URL exclusions list doesn't work

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/libsys-webforms#589]
I believe this is supposed to simply write to a text file. It's currently setup as a database table in the Rails app. We could keep it as a table, but we need to create the table in Oracle and have the eloader look there or have a process that writes the table data to a file.

**Comment by shelleydoljack** [comment]
Per Alissa, "I have never used the url exclusions list".

**Comment by shelleydoljack** [comment]
The current website writes data entered here to the file `/s/SUL/Bin/Eloader/Config/exclude_url_substrs`. @ahafele to confirm that we don't need to edit this file through the web interface anymore.

**Comment by ahafele** [comment]
Confirmed. I will write up documentation (for myself) to edit the file directly if needed.
