### ISSUE TITLE
Default package setting for holdings = SUL

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/libsys-webforms#598]
Is it easily possible for the package setting default to be SUL for holding code? It is currently LAW - presumably alphabetical.

**Comment by shelleydoljack** [comment]
@ahafele Yes, it's a simple ordering issue. Are there any other form values that need to be re-ordered so a certain default appears first in the selection list?

**Comment by ahafele** [comment]
Awesome. Nope, just that one. Thanks.
