### ISSUE TITLE
Please make jeanette an eloader "admin"

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/libsys-webforms#605]
Hi, Could you give jkalchik eloader package edit/add/test capabilities on morison and bodoni. If I remember correctly this has to be done in a table. She is already enabled to "manage eloader packages"

**Comment by dlrueda** [comment]
I updated the table for both morison and bodoni (libsys-webforms-dev and libsys-webforms-prod).  @ahafele  please have Jeanette test.

Will close, you can reopen if there's a problem
