### ISSUE TITLE
popup doesn't pop up when click Allow noBib on edifact invoice management menu

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/libsys-webforms#614]
Screen just kind of greys out instead of showing:

 
![image](https://user-images.githubusercontent.com/14914677/64654205-5ba0aa80-d3dd-11e9-8346-5200893c6917.png)

**Comment by jgreben** [comment]
Fixed by https://github.com/sul-dlss/libsys-webforms/pull/610/commits/84422ac3ff6c9b7a91472bd543e48e599f6fe32f in https://github.com/sul-dlss/libsys-webforms/pull/610
