### ISSUE TITLE
Cannot create expenditures report

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/libsys-webforms#622]
From the dev log:
> Started POST "/expenditure_reports" for 171.66.177.97 at 2019-09-18 15:02:53 -0700
> Processing by ExpenditureReportsController#create as HTML
>   Parameters: {"utf8"=>"✓", "authenticity_token"=>"<redacted>", "expenditure_report"=>{"email"=><redacted>, "fund_select"=>"fund_name_id", "fund"=>["<redacted>"], "fund_begin"=>"", "date_type"=>"calendar", "fy_start"=>"", "fy_end"=>"", "cal_start"=>"2016", "cal_end"=>"2018", "pd_start"=>"", "pd_end"=>"", "ckey_link"=>"0", "status"=>"REQUEST", "output_file"=>"exp_rpt1568844105", "message"=>"", "path_invlin_fund_keys"=>"", "date_request"=>"", "date_ran"=>""}, "commit"=>"Submit request"}
> Completed 500 Internal Server Error in 8ms (ActiveRecord: 2.2ms)
> 
> 
>   
> ActiveRecord::StatementInvalid (OCIError: ORA-01830: date format picture ends before converting entire input string: INSERT INTO "EXPENDITURES_LOG" ("DATE_REQUEST", "STATUS", "EMAIL", "TA_FUND_CODE", "OUTPUT_FILE", "CKEY_LINK") VALUES (:a1, :a2, :a3, :a4, :a5, :a6)):
>   
> app/controllers/expenditure_reports_controller.rb:18:in `create'

**Comment by jgreben** [comment]
Fixed by https://github.com/sul-dlss/libsys-webforms/pull/621/commits/dea745dea19d1b45404a908412353524678c610e

**Comment by shelleydoljack** [comment]
Confirming fix.
