### ISSUE TITLE
Cannot create expenditures with circ stats report

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/libsys-webforms#623]
From the dev log:

> Started GET "/assets/expenditures_with_circ_stats_reports.self-7e6d99529499a7bdef26f183c7af084424b21fe9259cca326ed13c6062d16789.js?body=1" for 171.66.177.97 at 2019-09-18 15:13:35 -0700
> Started POST "/expenditures_with_circ_stats_reports" for 171.66.177.97 at 2019-09-18 15:14:35 -0700
> Processing by ExpendituresWithCircStatsReportsController#create as HTML
>   Parameters: {"utf8"=>"✓", "authenticity_token"=>"<redacted>", "expenditures_with_circ_stats_report"=>{"email"=>"<redacted>", "fund_select"=>"fund_name_id", "fund"=>["<redacted>"], "fund_begin"=>"", "date_type"=>"calendar", "fy_start"=>"", "fy_end"=>"", "cal_start"=>"2018", "cal_end"=>"2019", "pd_start"=>"", "pd_end"=>"", "lib_array"=>["", "All Libraries"], "format_array"=>["", "All Formats"], "one_row_total"=>"1", "ckey_link"=>"0", "status"=>"REQUEST", "message"=>"", "output_file"=>"exp_rpt1568844815"}, "commit"=>"Submit request"}
> Completed 500 Internal Server Error in 6ms (ActiveRecord: 1.7ms)
> 
> 
>   
> ActiveRecord::StatementInvalid (OCIError: ORA-01830: date format picture ends before converting entire input string: INSERT INTO "EXPENDITURES_CIRC_LOG" ("DATE_REQUEST", "STATUS", "EMAIL", "TA_FUND_CODE", "ONE_ROW_TOTAL", "OUTPUT_FILE", "CKEY_LINK") VALUES (:a1, :a2, :a3, :a4, :a5, :a6, :a7)):
>   
> app/controllers/expenditures_with_circ_stats_reports_controller.rb:16:in `create'

**Comment by jgreben** [comment]
Fixed by https://github.com/sul-dlss/libsys-webforms/pull/621/commits/dea745dea19d1b45404a908412353524678c610e

**Comment by shelleydoljack** [comment]
This isn't working. I tried to create several reports with different funds selected and different fiscal year ranges and always get "There are no records" flash message. I even tried all SUL funds for a particular library and get the same "there are no records."

**Comment by shelleydoljack** [comment]
Using byebug `step`, it looks like the date_range_end is not getting set.
parameters sent on form submittal:
```
Parameters: {
  "utf8" => "✓",
  "authenticity_token" => "ABC",
  "expenditures_with_circ_stats_report" => {
    "email" => "sdoljack@stanford.edu",
    "fund_begin" => "All SUL Funds",
    "date_type" => "fiscal",
    "fy_start" => "FY 2016",
    "fy_end" => "FY 2019",
    "cal_start" => "",
    "cal_end" => "",
    "pd_start" => "",
    "pd_end" => "",
    "lib_array" => ["",
      "EAST-ASIA"
    ],
    "format_array" => ["",
      "All Formats"
    ],
    "one_row_total" => "1",
    "ckey_link" => "1",
    "status" => "REQUEST",
    "message" => "",
    "output_file" => "exp_rpt1569623357",
    "date_request" => "2019-09-27 15:29:17",
    "date_ran" => ""
  },
  "commit" => "Submit request"
}
1: @expenditures_with_circ_stats_report = #<ExpendituresWithCircStatsReport date_request: "2019-09-27 22:29:17",
date_ran: nil,
status: "REQUEST",
email: "sdoljack@stanford.edu",
ta_fund_code: nil,
date_range_start: nil,
date_range_end: nil,
libraries: nil,
formats: nil,
one_row_total: 1,
output_file: "exp_rpt1569623357",
message: "",
ckey_link: 1>
```
attributes set from model:
```
1: @expenditures_with_circ_stats_report = #<ExpendituresWithCircStatsReport date_request: "2019-09-27 22:29:17",
date_ran: nil,
status: "REQUEST",
email: "sdoljack@stanford.edu",
ta_fund_code: "All SUL Funds",
date_range_start: "2015-09-04 07:00:00",
date_range_end: nil,
libraries: "EAST-ASIA",
formats: "",
one_row_total: 1,
output_file: "exp_rpt1569623357",
message: "",
ckey_link: 1>
```

**Comment by shelleydoljack** [comment]
This works now. I created two reports, one with FY2016-FY2018 and another with FY2018-FY2020 and didn't get the "no records" flash message.
