### ISSUE TITLE
Filter by vendor drop-down doesn't work

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/libsys-webforms#629]
When viewing EDI invoices, there is a drop-down menu for filtering by vendor. It doesn't seem to work using Safari or Chrome. In Chrome, it looks like after selecting from the drop-down something is submitted to the server because the browser looks like it's loading a page, but then it just loads the whole list. In Safari, nothing seems to happen after selecting a vendor from the drop-down.

**Comment by jgreben** [comment]
Fixed by https://github.com/sul-dlss/libsys-webforms/commit/357c0f97b1218436125458dd3ff3af65b11fa4e3
