### ISSUE TITLE
Add optional New Current Location choice to Home Location change form

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/libsys-webforms#66]
![screen shot 2016-04-26 at 9 14 48 am](https://cloud.githubusercontent.com/assets/3093850/14825591/621616e4-0b8f-11e6-9f43-5c9e559e7417.png)

(not currently on this form)

**Comment by tallenaz** [comment]
@dlrueda is the new current location a unicorn_policy of type LOCN?

**Comment by dlrueda** [comment]
Yes, exactly as you described.

**Comment by jgreben** [comment]
Closed by #80
