### ISSUE TITLE
Fix date fields for browsers not HTML5-compatible (Edge and Safari)

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/libsys-webforms#704]
I test submitted a SAL3 batch request and even though the delivery start and deliver by date fields were filled in with default values `FEB/20/21` and `AUG/20/21` the form alerted me to fill in these dates. I used the datepicker and the date format was `MM/DD/YYYY` and the form was able to be submitted.

_Originally posted by @shelleydoljack in https://github.com/sul-dlss/libsys-webforms/pull/701#issuecomment-589799895_

**Comment by jgreben** [comment]
Closed by https://github.com/sul-dlss/libsys-webforms/pull/701
