### ISSUE TITLE
Remove obsolete libraries from Libsys-webforms reports

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/libsys-webforms#718]
In library drop down, we show the following libraries that no longer exist:

BIOLOGY
CHEMCMGENG
MATH-CS

Please remove from list.  Maybe this means removing from libs-locs table? (is that the actual table name?)

**Comment by jgreben** [comment]
UNI_LIBS_LOCS

**Comment by jgreben** [comment]
rows removed from table, so libsys-webforms is automatically updated.
